### ISSUE TITLE
Not detecting MPSM

### ISSUE THREAD

**Issue by Tomasu** [bruhmann/OctoPrint-EEPROM-MPSelectMini#4]
I've installed this plugin and have a MPSM, and it just says It doesn't work with my machine. I believe it said that for both this V2 and my previous V1.

**Comment by bruhmann** [comment]
If you can copy the error you see that would help.  Does it install property?  Do you see a firmware listed?  For example, on the settings page for the plugin, this shows up on mine "Firmware: Malyan 2.9".  Also, it needs to be connected to your printer and it takes a few moments for the plugin to properly load after the printer is connected or the page is first loaded.  I actually was just looking at mine and was surprised to see that error for several seconds and then finally everything loaded.

**Comment by Tomasu** [comment]
Here's the error: "Sorry. This plugin does not work with your machine. It has only been designed and tested with Malyan based firmware for the Malyan M200 and Monoprice Select Mini."

I browsed quickly at the source and noticed the version check, which does not catch my current fw version:

Recv: NAME. Malyan	VER: 4.0	MODEL: M200	HW: HH02
Recv: CLK:EXT BUILD: Aug 14 2017 16:46:00

This is fw 40.110.2.

**Comment by jbkuma** [comment]
I have the same issue with firmware 40.50

**Comment by bruhmann** [comment]
Unfortunately, motion control version 40 is not supported by the V1 and that's all I own.  I can't test any changes.  I'll try to make a branch that unblocks that version, but I'll need a tester before putting it in the main branch.

**Comment by bruhmann** [comment]
for anyone having this issue:

go to settings
select plugin manager
find the EEPROM Editor for MPSM in the installed plugins list and click the trash can for it
click "restart now" button in the announcement that pops up on the right, click proceed
wait for restart, reload
go to settings
select plugin manager
click "Get More..." button
in "... from URL" box, paste this URL:
https://github.com/bruhmann/OctoPrint-EEPROM-MPSelectMini/archive/v40dev.zip
click install button
restart again
test
let me know how it went

**Comment by bruhmann** [comment]
just now made another small change that might help, to that same branch

**Comment by Tomasu** [comment]
Thanks for looking at it. I'll try it soonish and let you know.

**Comment by jbkuma** [comment]
Works perfectly, thank you!

Jason "Kuma" Brinkerhoff
*Mad Science Workshoppe, *proprietor
http://jbkuma.com/workshoppe

On Sat, Sep 23, 2017 at 2:49 PM, Thomas Fjellstrom <notifications@github.com

**Comment by bruhmann** [comment]
in the master branch now.  Reinstalling normally should fix it.  (There was a bug that may cause notifications for an upgrade to fail.)
